# **Basic 6 step applicable for almost all machine learing model**

**Importing the Libraries**

In [1]:
#Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

**Import the Dataset**

In [2]:
#Importing the Dataset
dataset = pd.read_csv("../input/datacsv/Data.csv")
X = dataset.iloc[:, :-1].values           # saving the independent variable as a 2D array
y = dataset.iloc[:, -1].values            #saving the dependent variable as a vector or 1D array
print(X)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


**Handling Missing Values**

In [3]:
#Handling Missing Values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')
# imputer.fit(X[:, [1,2]])
X[:, [1,2]] = imputer.fit_transform(X[:, [1,2]])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


**Encoding the categorical variable**

In [4]:
#Encoding the categorical varible
#Encoding the Independent variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = ct.fit_transform(X)
print(X)

#Encoding the dependent variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1 0 1]


**Transforming the dataset into test set and training set**

In [5]:
#Transforming the dataset into test set and train set
from sklearn.model_selection import train_test_split
# help(train_test_split)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=8)
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[1.0 0.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 0.0 1.0 38.0 61000.0]]
[1 0 0 1 1 1 1 0]
[[0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]]
[0 0]


**Feature Scaling**

In [6]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])
print(X_train)
print(X_test)

[[1.0 0.0 0.0 -0.058222250973958195 0.4476695040387244]
 [1.0 0.0 0.0 1.0285931005399283 0.9866695757910343]
 [0.0 1.0 0.0 -1.1450376024878446 -0.9537306825172813]
 [1.0 0.0 0.0 -0.3687409228350686 -0.5225306251154334]
 [1.0 0.0 0.0 1.649630444262149 1.741269676244268]
 [0.0 0.0 1.0 -1.6108156102795101 -1.6005307686200532]
 [0.0 1.0 0.0 0.4075557568177074 0.1003139022427917]
 [0.0 0.0 1.0 0.09703708495659699 -0.19913058206404746]]
[[0.0 1.0 0.0 1.9601491161232594 2.172469733646116]
 [0.0 0.0 1.0 0.21779434623591784 -1.1693307112182052]]
