In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/various-expenses-and-the-profits-of-50-startups/50_Startups.csv


In [2]:
#Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#Importing the dataset
df = pd.read_csv('../input/various-expenses-and-the-profits-of-50-startups/50_Startups.csv')
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [4]:
#Spliting the datasset into Independent and dependent variable
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
print(x)
print(y)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

In [5]:
#Handling categorical variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encode', OneHotEncoder(), [3])], remainder='passthrough')
x = ct.fit_transform(x)
print(x)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

In [6]:
#Spliting our data into training set and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15, random_state=0)
print(x_train)
print(y_train)
print(x_test)
print(y_test)

[[0.0 1.0 0.0 73994.56 122782.75 303319.26]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 1.0 0.0 55493.95 103057.49 214634.81]
 [0.0 0.0 1.0 46014.02 85047.44 205517.64]
 [0.0 1.0 0.0 75328.87 144135.98 134050.07]
 [1.0 0.0 0.0 46426.07 157693.92 210797.67]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 1000.23 124153.04 1903.93]
 [0.0 0.0 1.0 542.05 51743.15 0.0]
 [0.0 0.0 1.0 65605.48 153032.06 107138.38]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [0.0 1.0 0.0 61994.48 115641.28 91131.24]
 [1.0 0.0 0.0 63408.86 129219.61 46085.25]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [1.0 0.0 0.0 23640.93 96189.63 148001.11]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 15505.73 127382.3 35534.17]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [1.0 0.0 0.0 64664.71 139553.16 137962.62]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [0.

In [7]:
#Training our machine
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [8]:
#Predictions
y_pred = regressor.predict(x_test)
print(y_pred.shape)
print(y_test.shape)

(8,)
(8,)


In [9]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test), 1)), axis=1))

[[102778.64 103282.38]
 [132460.8  144259.4 ]
 [131978.66 146121.95]
 [ 71514.72  77798.83]
 [177931.87 191050.39]
 [116097.91 105008.31]
 [ 67761.74  81229.06]
 [ 98927.52  97483.56]]


In [10]:
np.delete
np.hstack

<function numpy.hstack(tup)>

# Now Optimizing our code with Backward Elimination

In [11]:
import statsmodels.api as sm
x_opt = np.append(arr=np.ones((50,1), dtype=int), values=x.astype(float), axis=1)
x_opt = x_opt[:, [0,2,3,4,5,6]]
# print(x_opt)
regressor_OLS = sm.OLS(endog=y, exog=x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Sat, 31 Jul 2021   Prob (F-statistic):           1.34e-27
Time:                        15:58:43   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.013e+04   6884.820      7.281      0.000    3.62e+04     6.4e+04
x1           198.7888   3371.007      0.059      0.953   -6595.030    6992.607
x2           -41.8870   3256.039     -0.013      0.990   -6604.003    6520.229
x3             0.8060      0.046     17.369      0.000       0.712       0.900
x4            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x5             0.0270      0.017      1.574      0.123      -0.008       0.062
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.45e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.45e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [12]:
x_opt = x_opt[:, [0,1,3,4,5]]
# print(x_opt)
regressor_OLS = sm.OLS(endog=y, exog=x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Sat, 31 Jul 2021   Prob (F-statistic):           8.49e-29
Time:                        15:58:43   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.011e+04   6647.870      7.537      0.000    3.67e+04    6.35e+04
x1           220.1585   2900.536      0.076      0.940   -5621.821    6062.138
x2             0.8060      0.046     17.606      0.000       0.714       0.898
x3            -0.0270      0.052     -0.523      0.604      -0.131       0.077
x4             0.0270      0.017      1.592      0.118      -0.007       0.061
==============================================================================
Omnibus:                       14.758   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.172
Skew:                          -0.948   Prob(JB):                     2.53e-05
Kurtosis:                       5.563   Cond. No.                     1.40e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [13]:
x_opt = x_opt[:, [0,2,3,4]]
# print(x_opt)
regressor_OLS = sm.OLS(endog=y, exog=x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Sat, 31 Jul 2021   Prob (F-statistic):           4.53e-30
Time:                        15:58:43   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.012e+04   6572.353      7.626      0.000    3.69e+04    6.34e+04
x1             0.8057      0.045     17.846      0.000       0.715       0.897
x2            -0.0268      0.051     -0.526      0.602      -0.130       0.076
x3             0.0272      0.016      1.655      0.105      -0.006       0.060
==============================================================================
Omnibus:                       14.838   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.442
Skew:                          -0.949   Prob(JB):                     2.21e-05
Kurtosis:                       5.586   Cond. No.                     1.40e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [14]:
x_opt = x_opt[:, [0,1,3]]
# print(x_opt)
regressor_OLS = sm.OLS(endog=y, exog=x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Sat, 31 Jul 2021   Prob (F-statistic):           2.16e-31
Time:                        15:58:44   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464      0.000    4.16e+04    5.24e+04
x1             0.7966      0.041     19.266      0.000       0.713       0.880
x2             0.0299      0.016      1.927      0.060      -0.001       0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.161
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

***Automatic Backward Elimination***

In [15]:
import statsmodels.api as sm
def backward_elimination(x, sl):
    x = sm.add_constant(x)
    numV = len(x[0])
    for i in range(0, numV):
        regressor_OLS = sm.OLS(y, x.astype(float)).fit()
        max_p = max(regressor_OLS.pvalues).astype(float)
        if max_p > sl:
            for j in range(0, numV-i):
                if regressor_OLS.pvalues[j].astype(float) == max_p:
                    x = np.delete(x, j, 1)
    regressor_OLS.summary()
    return x

x_opt = x[:, [0,1,2,3,4,5]]
SL = 0.05
x_model = backward_elimination(x_opt, SL)
print(x_model)

[[1.0 0.0 0.0 1.0 165349.2]
 [1.0 1.0 0.0 0.0 162597.7]
 [1.0 0.0 1.0 0.0 153441.51]
 [1.0 0.0 0.0 1.0 144372.41]
 [1.0 0.0 1.0 0.0 142107.34]
 [1.0 0.0 0.0 1.0 131876.9]
 [1.0 1.0 0.0 0.0 134615.46]
 [1.0 0.0 1.0 0.0 130298.13]
 [1.0 0.0 0.0 1.0 120542.52]
 [1.0 1.0 0.0 0.0 123334.88]
 [1.0 0.0 1.0 0.0 101913.08]
 [1.0 1.0 0.0 0.0 100671.96]
 [1.0 0.0 1.0 0.0 93863.75]
 [1.0 1.0 0.0 0.0 91992.39]
 [1.0 0.0 1.0 0.0 119943.24]
 [1.0 0.0 0.0 1.0 114523.61]
 [1.0 1.0 0.0 0.0 78013.11]
 [1.0 0.0 0.0 1.0 94657.16]
 [1.0 0.0 1.0 0.0 91749.16]
 [1.0 0.0 0.0 1.0 86419.7]
 [1.0 1.0 0.0 0.0 76253.86]
 [1.0 0.0 0.0 1.0 78389.47]
 [1.0 0.0 1.0 0.0 73994.56]
 [1.0 0.0 1.0 0.0 67532.53]
 [1.0 0.0 0.0 1.0 77044.01]
 [1.0 1.0 0.0 0.0 64664.71]
 [1.0 0.0 1.0 0.0 75328.87]
 [1.0 0.0 0.0 1.0 72107.6]
 [1.0 0.0 1.0 0.0 66051.52]
 [1.0 0.0 0.0 1.0 65605.48]
 [1.0 0.0 1.0 0.0 61994.48]
 [1.0 0.0 0.0 1.0 61136.38]
 [1.0 1.0 0.0 0.0 63408.86]
 [1.0 0.0 1.0 0.0 55493.95]
 [1.0 1.0 0.0 0.0 46426.07]
 [1.0 0.0 0

***Automatic Backward Elimination with p-values and Adjusted-R square***

In [16]:
import statsmodels.api as sm
def backward_elimination_adjR(x, sl):
    x = sm.add_constant(x)
    temp = np.zeros(x.shape).astype(int)
    numV = len(x[0])
    for i in range(0, numV):
        regressor_OLS = sm.OLS(y, x.astype(float)).fit()
        max_p = max(regressor_OLS.pvalues).astype(float)
        adjR_before = regressor_OLS.rsquared_adj.astype(float)
        if max_p > sl:
            for j in range(0, numV-i):
                if regressor_OLS.pvalues[j].astype(float) == max_p:
                    temp[:, j] = x[:, j]
                    x = np.delete(x, j, 1)
                    tmp_regressor = sm.OLS(y, x.astype(float)).fit()
                    adjR_after = regressor_OLS.rsquared_adj.astype(float)
                    if (adjR_before>=adjR_after):
                        x_rollback = np.hstack((x, temp[:, [j]]))
#                         x_rollback = np.delete(x_rollback, j ,1)
                        print(regressor_OLS.summary())
                        return x_rollback
                    else:
                        continue
    print(regressor_OLS.summary())
    return x

x_opt = x[:, [0,1,2,3,4,5]]
SL = 0.05
x_model = backward_elimination_adjR(x_opt, SL)
print(x_model)
print(x_model.shape)

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Sat, 31 Jul 2021   Prob (F-statistic):           1.34e-27
Time:                        15:58:44   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       3.763e+04   5073.636      7.417      0.0

In [17]:
xz = np.ones((5,2))
raf = np.zeros((5,2))
xz = np.hstack((xz, raf))
xz = np.hstack((xz, np.ones((5,3))))
print(xz)

[[1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 0. 0. 1. 1. 1.]]


In [18]:
temp = np.zeros(xz.shape).astype(int)
temp[:,1] = xz[:, 1]
xz = np.delete(xz, 1,1)
x_r = np.hstack((xz, temp[:, [1]]))
# x_r = np.delete(x_r,1,1)
print(x_r)

[[1. 0. 0. 1. 1. 1. 1.]
 [1. 0. 0. 1. 1. 1. 1.]
 [1. 0. 0. 1. 1. 1. 1.]
 [1. 0. 0. 1. 1. 1. 1.]
 [1. 0. 0. 1. 1. 1. 1.]]


In [19]:
temp = np.zeros(xz.shape).astype(int)
temp[:,1] = xz[:, 1]
xz = np.delete(xz, 1,1)
x_r = np.hstack((xz, temp[:, [1]]))
# x_r = np.delete(x_r,1,1)
print(x_r)

[[1. 0. 1. 1. 1. 0.]
 [1. 0. 1. 1. 1. 0.]
 [1. 0. 1. 1. 1. 0.]
 [1. 0. 1. 1. 1. 0.]
 [1. 0. 1. 1. 1. 0.]]
